apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: engineering-symbols
spec:
    environments:
        - name: prod
          runAsNonRoot: true
          build:
              from: master
        - name: dev
          runAsNonRoot: true
          build:
              from: develop
    # build:
    #     from: master
    # environments:
    #     - name: prod
    #       runAsNonRoot: true
    #       build:
    #           from: master
    components:
        - name: frontend
          publicPort: http
          src: .
          ports:
              - name: http
                port: 3000
        - name: web
          publicPort: http
          src: web
          ports:
              - name: http
                port: 3000
    dnsAppAlias:
        environment: prod
        component: frontend
    dnsExternalAlias:
        - alias: engineering-symbols.equinor.com
          environment: prod
          component: frontend
        - alias: engineering-symbols-web.equinor.com
          environment: prod
          component: web
        - alias: symbols.equinor.com
          environment: dev
          component: frontend
        - alias: symbols-web.equinor.com
          environment: dev
          component: web
