apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: engineering-symbols
spec:
    environments:
        - name: prod
          build:
              from: master
        - name: dev
          build:
              from: develop
    # build:
    #     from: master
    # environments:
    #     - name: prod
    #       runAsNonRoot: true
    #       build:
    #           from: master
    components:
        - name: storybook
          publicPort: http
          src: ./package
          ports:
              - name: http
                port: 3000
        - name: web
          publicPort: http
          src: ./web
          ports:
              - name: http
                port: 3000
    dnsAppAlias:
        environment: prod
        component: storybook
