apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: engineering-symbols
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: dev
      build:
        from: develop
  build:
      secrets:
        - MSAL_CLIENT_ID
        - MSAL_AUTHORITY
        - API_SCOPE
  components:
    - name: storybook
      publicPort: http
      src: ./package
      environmentConfig:
        - environment: prod
      ports:
        - name: http
          port: 3000
    - name: web
      publicPort: http
      src: ./web
      environmentConfig:
        - environment: prod
      ports:
        - name: http
          port: 3000
      secrets:
        - NEXT_PUBLIC_MSAL_CLIENT_ID
        - NEXT_PUBLIC_MSAL_AUTHORITY
        - NEXT_PUBLIC_API_SCOPE
    - name: webdev
      publicPort: http
      src: ./web
      environmentConfig:
        - environment: dev
      ports:
        - name: http
          port: 3000
      secrets:
        - NEXT_PUBLIC_MSAL_CLIENT_ID
        - NEXT_PUBLIC_MSAL_AUTHORITY
        - NEXT_PUBLIC_API_SCOPE
  dnsExternalAlias:
    - alias: engineering-symbols.equinor.com
      environment: prod
      component: web
  dnsAppAlias:
    environment: prod
    component: storybook
