apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: engineering-symbols
spec:
    environments:
        - name: prod
          build:
              from: master
        - name: dev
          build:
              from: develop
    # build:
    #     from: master
    # environments:
    #     - name: prod
    #       runAsNonRoot: true
    #       build:
    #           from: master
    components:
        - name: prod
          publicPort: http
          src: prod
          ports:
              - name: http
                port: 3000
        - name: dev
          publicPort: http
          src: dev
          ports:
              - name: http
                port: 3000
    dnsAppAlias:
        environment: prod
        component: frontend
    dnsExternalAlias:
        - alias: engineering-symbols.equinor.com
          environment: prod
          component: prod
        - alias: dev-engineering-symbols.equinor.com
          environment: dev
          component: dev
