apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: engineering-symbols
spec:
    build:
        secrets:
            - GH_TOKEN
    environments:
        - name: prod
          build:
              from: master
    components:
        - name: frontend
          publicPort: http
          src: src
          ports:
              - name: http
                port: 3000
    dnsAppAlias:
        environment: prod
        component: frontend
    dnsExternalAlias:
        - alias: engineering-symbols.equinor.com
          environment: prod
          component: frontend
