import Head from 'next/head';
import type { AppProps } from 'next/app';
import { HeaderComponent } from '../components';
import { ContainerStyled } from '../styles/Home.styles';

import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<ContainerStyled>
			<Head>
				<title>1Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="robots" content="noindex,nofollow" />
			</Head>

			<HeaderComponent />
			<Component {...pageProps} />
			<footer>License</footer>
		</ContainerStyled>
	);
}

export default MyApp;
