import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Typography, Chip } from '@equinor/eds-core-react';

import styles from '../styles/Home.module.css';

import { getGitHubReposResponse } from '../helpers';

const Home: NextPage = () => {
	const [data, setData] = useState<any>([]);

	useEffect(() => {
		const getData = async () => {
			const res = await getGitHubReposResponse();

			setData(res);
		};

		getData();
	}, []);

	console.log(89, data);

	return (
		<div className={styles.container}>
			<Head>
				<title>1Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="robots" content="noindex,nofollow" />
			</Head>

			<header className={styles.header}>
				<div className={styles.logoWrap}>
					<Link href="/">
						<a className={styles.headerLogo}>
							<Typography variant="h1_bold">Engineering symbols</Typography>
						</a>
					</Link>
					<Link href="/changelog">
						<a>{data.length > 0 && <Chip variant="active">{data[0].name}</Chip>}</a>
					</Link>
				</div>

				<nav className={styles.nav}>
					<ul>
						<li className={styles.availableList}>
							<Link href="/icons">
								<a>Icon</a>
							</Link>
						</li>
						<li className={styles.availableList}>
							<Link href="/documentation">
								<a>Documentation</a>
							</Link>
						</li>
					</ul>
				</nav>

				<p>Designed and built with ❤️</p>
			</header>

			<main className={styles.main}>
				<div className={styles.hero}>
					<Typography variant="h1">
						<strong>Your new Engineering symbols library.</strong>
					</Typography>
					<p className={styles.description}>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
						enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					</p>

					<div className={styles.infoBoxes}>
						<div className={styles.infoBox}>
							<Typography variant="h4">
								<strong>100%</strong>
							</Typography>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>
						</div>
						<div className={styles.infoBox}>
							<Typography variant="h4">
								<strong>1077</strong>
							</Typography>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>
						</div>
						<div className={styles.infoBox}>
							<Typography variant="h4">
								<strong>10.9k</strong>
							</Typography>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>
						</div>
						<div className={styles.infoBox}>
							<Typography variant="h4">
								<strong>100 mil.</strong>
							</Typography>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>
						</div>
					</div>

					<ul className={styles.availableList}>
						<li className={styles.availableListText}>
							<p>Available for:</p>
						</li>
						<li className={styles.availableListReact}>
							<Image src="/image/react.png" layout="fill" alt="hello" />
						</li>
						<li className={styles.availableListFigma}>
							<Image src="/image/figma.png" layout="fill" alt="hello" />
						</li>
						<li className={styles.availableListCode}>
							<Image src="/image/html-coding.png" layout="fill" alt="hello" />
						</li>
						<li className={styles.availableListFlutter}>
							<Image src="/image/flutter.png" layout="fill" alt="hello" />
						</li>
						<li className={styles.availableListAdobe}>
							<Image src="/image/adobe-illustrator.png" layout="fill" alt="hello" />
						</li>
					</ul>
				</div>
			</main>

			<footer className={styles.footer}>License</footer>
		</div>
	);
};

export default Home;
